// Every piece of writing the agent does, streamed token by token.
import { sse, guard, body, llmStream } from "./_lib.js";
export const config = { runtime: "edge" };

const brandBlock = (b = {}) => `Brand: ${b.name} (${b.site || "-"})\nCategory: ${b.category || "-"}\nOffer: ${b.offer || "-"}\nBuyers: ${b.audience || "-"}\nMarket: ${b.market || "global"}\nCompetitors: ${(b.competitors || []).join(", ") || "-"}${b.facts?.length ? "\nFacts from their site: " + b.facts.join("; ") : ""}`;

const FOCUS = { research: "half informational (exploring the problem and options), 30% commercial (comparing), 20% transactional (ready to buy or book)", compare: "a quarter informational, half commercial (comparisons, alternatives, best-of lists), a quarter transactional", action: "a quarter informational, a quarter commercial, half transactional (buying, booking, hiring, signing up)" };
const PROMPTS = {
  topics: ({ profile, exclude = [] }) => `You plan AI-visibility tracking for a company.\n${brandBlock(profile)}${profile.products?.length ? "\nProducts and services: " + profile.products.join("; ") : ""}\n\nList ${exclude.length ? 3 : 5} topics buyers research in AI assistants where this company should be recommended. Each topic is a 2-5 word noun phrase naming a product line, service or buyer need (not the brand name), e.g. "AI strategy consulting". ${exclude.length ? "Don't repeat: " + exclude.join("; ") + "." : ""}\nOutput one topic per line, nothing else.`,
  topicQuestions: ({ profile, topics = [], perTopic = 3, focus = "action", exclude = [] }) => `You are an answer-engine-optimisation strategist.\n${brandBlock(profile)}\nPersonas: ${(profile.personas || []).join("; ") || profile.audience || "-"}\n\nFor EACH of these topics write ${perTopic} questions real buyers type into ChatGPT or Perplexity${profile.market ? " in " + profile.market : ""}:\n${topics.map((t) => "- " + t).join("\n")}\n\nMix intents: ${FOCUS[focus] || FOCUS.action}. Include best-for, alternatives to a named competitor and A vs B between competitors where natural. Never include "${profile.name}" in a question. Write them the way people actually type, as the persona would ask.${exclude.length ? "\nDon't repeat these:\n" + exclude.slice(0, 40).join("\n") : ""}\n\nOutput exactly one per line, no numbering, in this format:\ntopic | intent | persona | question\nwhere topic is copied exactly from the list, intent is one of: informational, commercial, transactional, and persona is one of the personas.`,
  sentiment: ({ profile, items = [] }) => `Score how positively each AI answer talks about each listed brand, 0-100 (0 = clearly negative or warned against, 50 = neutral factual mention, 70-85 = recommended with praise like trusted, leading, best for, 90+ = strongly recommended as the top choice). Judge only the wording about that brand.\nThe tracked company is ${profile?.name || "-"}.\n\n${items.map((it) => `[${it.id}] brands: ${(it.brands || []).join(", ")}\n${String(it.text || "").slice(0, 900)}`).join("\n\n")}\n\nReply with JSON only, one key per answer id, mapping each listed brand to its score: {"a0":{"Brand":72,"Other":60}}`,
  questions: ({ profile, count = 12 }) => `You are an answer-engine-optimisation strategist.\n${brandBlock(profile)}\n\nWrite ${count} questions real buyers type into ChatGPT or Perplexity right before choosing a ${profile.category}${profile.market ? " in " + profile.market : ""}. Mix intents: best-for, alternatives to a named competitor, A vs B between competitors, problem-led "how do I", and budget or location. Never include "${profile.name}" in a question. Write them the way people actually type.\n\nOutput exactly one per line, no numbering, in this format:\nintent | question\nwhere intent is one of: best, alternatives, comparison, problem, local`,
  insights: ({ profile, digest }) => `You are White Pettle, an AI-visibility analyst. Explain to the founder of ${profile.name} what is happening in AI answers and WHY, based only on this data.\n\n${brandBlock(profile)}\n\nDATA\n${digest}\n\nWrite exactly 5 insights in markdown, each a bullet starting with a short bold headline, then one or two sentences with specific numbers, names, pages and questions from the data. Cover: the overall picture, why the top rival wins (which pages carry it), the cheapest gap to close, a pattern across questions, and the single highest-leverage move this week. No preamble.`,
  pitch: ({ profile, t }) => `Write a short, honest outreach email so ${profile.name} gets genuinely included on a page that AI assistants cite. No flattery, no fake claims, no payment offers.\n\n${brandBlock(profile)}\n\nTarget page: ${t.url}\nTitle: ${t.title}\nAuthor: ${t.author || "unknown"}\nRivals already on the page: ${(t.rivals || []).join(", ") || "none found"}\nBuyer questions where AI cites this page: ${(t.questions || []).join("; ")}\nPage excerpt: ${(t.excerpt || "").slice(0, 1000)}\n\nFormat exactly:\nSubject: <max 9 words>\n\n<70-120 word body that references something specific on the page, says why readers benefit, and proposes the exact addition (a row, a line, a quote, a data point). Sign as [Your name].>`,
  article: ({ profile, question, rivals, siteText }) => `Write a publish-ready article for ${profile.name}'s website, built to be the page AI assistants cite for: "${question}"\n\n${brandBlock(profile)}\nCompanies AI currently recommends for this: ${(rivals || []).join(", ") || "-"}\nWhat the site says:\n${(siteText || "").slice(0, 3000)}\n\nRules: Markdown. 1,000-1,400 words. '# Title'. The first paragraph is a 40-60 word direct answer. Use question-style H2s, one fair comparison table that includes ${profile.name}, a 'How to choose' checklist, and a 5-question FAQ. Never invent statistics, clients, quotes or prices. Write [TODO: add real number] or [TODO: add client quote] instead. End with 'Last updated: <Month Year>'.`,
  fixpack: ({ profile, page, text }) => `You optimise a web page so AI assistants quote it.\n${brandBlock(profile)}\nPage: ${page.url}\nTitle: ${page.title}\nFailing checks: ${(page.fails || []).join(", ")}\nPage text: ${(text || "").slice(0, 6000)}\n\nWrite in markdown:\n**Should win:** <the buyer question this page should own>\n\n**New opening paragraph** (40-60 words, answers that question directly)\n\n**Question headings to add** (5 bullets)\n\n**FAQ to add** (5 Q&As, answers under 45 words)\n\n**Other fixes** (3-5 specific bullets)\n\nNever invent numbers. Use [TODO] where proof is needed.`,
  assets: ({ profile, pages }) => `Create AI-search assets for this company using only facts given.\n${brandBlock(profile)}\nKey pages:\n${(pages || []).map((p) => `- ${p.title} | ${p.url}`).join("\n")}\n\nReply with JSON only: {"llms_txt":"a complete llms.txt in markdown: '# Name', '> one-sentence summary', a short paragraph of key facts, then '## Key pages' with '- [Title](url): what it covers'","org_schema":{an Organization JSON-LD object with @context, @type, name, url, description}}`,
  perception: ({ profile, answers }) => `Compare what AI assistants say about a company with what the company says about itself.\n${brandBlock(profile)}\n\nAI answers:\n${(answers || []).map((a) => `Q: ${a.q}\nA: ${String(a.a).slice(0, 1500)}`).join("\n\n")}\n\nReply with JSON only: {"summary":"two plain sentences on how AI describes the company today","recognised":true|false,"claims":[{"claim":"a specific claim the AI made","verdict":"accurate|unsupported|wrong|outdated","fix":"what to publish to correct or reinforce it, max 20 words"}]}. Up to 8 claims.`,
  chat: ({ context, history, question }) => `You are White Pettle, a sharp, friendly AI-visibility strategist helping a company get recommended by ChatGPT, Perplexity and Gemini. Use the data below. Be concrete and brief: under 170 words unless asked to write something. Name specific pages, rivals and questions from the data. Never invent numbers. Write requested content ready to paste.\n\nDATA\n${String(context || "").slice(0, 14000)}\n\nCONVERSATION\n${(Array.isArray(history) ? history : []).slice(-8).map((m) => (m?.role === "me" ? "User: " : "Assistant: ") + String(m?.text || "").slice(0, 4000)).join("\n\n")}\n\nUser: ${String(question || "").slice(0, 4000)}\nAssistant:`,
};

export default async function handler(req) {
  const denied = guard(req); if (denied) return denied;
  const { kind, data = {} } = await body(req);
  return sse(async (send) => {
    const p = PROMPTS[kind]; if (!p) throw new Error("Unknown request");
    const text = await llmStream(p(data), (d) => send("delta", { text: d }), { max: kind === "article" ? 5000 : kind === "sentiment" ? 4000 : 2500 });
    send("final", { text });
  });
}
